---
    - name: Encode SA  password provided by customer
      shell: echo {{ sql_sa_pwd | b64encode }}
      register: encoded_value

    - name: create secret for SA password
      kubernetes.core.k8s:
        state: present
        definition:
           apiVersion: v1
           kind: Secret
           metadata:
              name: "{{ sql_pod_name  + '-secret' }}"
              namespace: "{{ sql_projectname_ns }}"
           type: Opaque
           data:
             SA_PASSWORD: "{{ encoded_value.stdout }}"

